# fly.toml app configuration file generated for project-nexus on 2025-05-27T16:59:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'project-nexus'
primary_region = 'yyz'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[deploy]
  strategy = "rolling"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '2s'
    timeout = '1s'
    grace_period = '1s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
